var myVariable = "value";
var stringPartLetters ="Letters";
var stringPartNumbers ="Numbers";
var stringPartCharacters ="characters";
var myFullString = "A string may contian as many "+stringPartLetters+", "+stringPartNumbers+" and "+stringPartCharacters+" as you want.";
console.log(myFullString);
var count = 10;
var multiplier = 20;
var calculateVariables = "I have "+(count * multiplier)+" friends on 'facebook'.";
console.log(calculateVariables);
var stringYear = "In the year " + multiplier.toSstring() + count.toString() + ",most of us were over 3 years old.";
console.log(stringyear);
var myColorarray = ['orange', 'Red', 'Yellow', 'Green'];
var myColor = "My favorite color is " + myColorArray[2];
console.log(mycolor);
var myFruitColorArray = [ ['Apples', 'Bannanas', 'Grapes'], ['Red', 'Yellow', 'Green'] ];